package gbon_test

import (
	"bytes"
	"encoding/hex"
	"errors"
	"fmt"
	"io"
	"math/rand"
	"os"
	"path/filepath"
	"reflect"
	"strconv"
	"strings"
	"testing"

	"github.com/gbon-format/gbon-go"
)

// FuzzDecode: arbitrary input into a stateless
// Unmarshal terminates with success or exactly one sentinel — never a
// panic, never a hang; budgets are the progress measure. Seeds
// are the golden corpus g1..g50 plus truncations and byte flips, and
// crafted allocation-bomb headers (u32/u32-backing-length container
// claims) that mutation cannot reach from the legal corpus.
func FuzzDecode(f *testing.F) {
	for _, tc := range golden {
		wb, err := hex.DecodeString(strings.ReplaceAll(tc.want, " ", ""))
		if err != nil {
			f.Fatalf("seed hex %s: %v", tc.name, err)
		}
		full := append(append([]byte{}, hdr...), wb...)
		f.Add(full)
		if len(full) > 8 {
			f.Add(full[:len(full)/2])
			flip := append([]byte{}, full...)
			flip[len(flip)/2] ^= 0xFF
			f.Add(flip)
		}
	}
	// crafted u32-L ARRAY/BLOB claims (tiny input, huge backing)
	f.Add([]byte{0x67, 0x62, 0x6F, 0x6E, 0x00, 0x00, // header
		0xD1, 0x67, '[', ']', 'i', 'n', 't', '6', '4',
		0xD8, 0x65, 'i', 'n', 't', '6', '4', 0x08,
		0x8E, 0x05, 0xF5, 0xE0, 0x00, // L = 10^8, E missing → truncated
	})
	f.Add([]byte{0x67, 0x62, 0x6F, 0x6E, 0x00, 0x00,
		0xD1, 0x67, '[', ']', 'i', 'n', 't', '6', '4',
		0xD8, 0x65, 'i', 'n', 't', '6', '4', 0x08,
		0x8E, 0x05, 0xF5, 0xE0, 0x00, 0x90, 0x04, // g51 whole
	})
	// Kind-15, decimal form-2, and ext-argument surfaces.
	f.Add([]byte{0x67, 0x62, 0x6F, 0x6E, 0x00, 0x00,
		0xDC, 0x0F, 0x67, 'b', 'i', 'g', '.', 'I', 'n', 't', 0x0A})
	f.Add([]byte{0x67, 0x62, 0x6F, 0x6E, 0x00, 0x00,
		0xDC, 0x0F, 0x67, 'b', 'i', 'g', '.', 'I', 'n', 't',
		0x10, 0x09, 0x02, 0, 0, 0, 0, 0, 0, 0, 0})
	f.Add([]byte{0x67, 0x62, 0x6F, 0x6E, 0x00, 0x00,
		0xDA, 0x67, 'f', 'l', 'o', 'a', 't', '6', '4', 0x0C, 0x10,
		0x42, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0})
	f.Add([]byte{0x67, 0x62, 0x6F, 0x6E, 0x00, 0x00,
		0x82, 0x10, 0x09, 0x02}) // ext selector in a bare length position
	// u64-L claim: 2^40 backing in 9 bytes of ARG
	f.Add([]byte{0x67, 0x62, 0x6F, 0x6E, 0x00, 0x00,
		0xD1, 0x67, '[', ']', 'i', 'n', 't', '6', '4',
		0xD8, 0x65, 'i', 'n', 't', '6', '4', 0x08,
		0x8F, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	})
	// Crafted seeds generated by the class table — one deterministic
	// stream per coverage subclass of the crafted corpus (a/b/c),
	// enumerated from the same table the oracle tests walk
	// (the f.Add loop and TestCraftedClassCounts share the single
	// source craftedSeeds()/craftedValidTopo()).
	for _, tc := range craftedSeeds() {
		f.Add(tc.stream)
	}
	for _, tc := range craftedValidTopo() {
		// cycle/DAG twins: map-self, slice-self, mutual, DAG-shared —
		// decode into interface targets needs the
		// registry, but as fuzz input they must still yield only the
		// three sentinels (stateless path: ErrUnsupported on concrete
		// interface positions is in the sentinel set above).
		f.Add(tc.stream)
	}
	f.Fuzz(func(t *testing.T, data []byte) {
		var v any
		err := gbon.Unmarshal(data, &v)
		if err == nil {
			return
		}
		if !errors.Is(err, gbon.ErrFormat) &&
			!errors.Is(err, gbon.ErrBudget) &&
			!errors.Is(err, gbon.ErrUnsupported) &&
			!errors.Is(err, gbon.ErrIO) {
			t.Fatalf("non-sentinel error: %v", err)
		}
		var ae *gbon.Error
		if !errors.As(err, &ae) {
			t.Fatalf("error not As-recoverable: %v", err)
		}
		if ae.Class() == "" || ae.Offset < 0 {
			t.Fatalf("error lacks class/offset: %+v", ae)
		}
		if strings.Contains(err.Error(), "\n") {
			t.Fatalf("%v not one line", err)
		}
	})
}

// FuzzRT: generated values with interface
// positions — dynamic types from the registered set (unhashable map/slice
// in VALUE positions), typed nils, iface-keyed maps, shared
// pointers — round-trip through a registered Decoder. Map
// self-reference and slice self-reference through any positions (Marshal
// must terminate on them — the fatal-stack-overflow class).
func FuzzRT(f *testing.F) {
	f.Add([]byte{1})
	f.Add([]byte{2, 3})
	f.Add([]byte{4, 5, 6})
	f.Fuzz(func(t *testing.T, data []byte) {
		seed := int64(len(data))
		if len(data) > 0 {
			seed = seed<<8 | int64(data[0])
		}
		v := rtGen(seed)
		b, err := gbon.Marshal(v)
		if err != nil {
			t.Fatalf("marshal %s: %v", safeDesc(v), err)
		}
		dec := gbon.NewDecoder(bytes.NewReader(b))
		if err := dec.Register(int64(0), int32(0), X{}, &X{}, "", map[string]int{}, map[any]int{}, []int64{}, map[string]any{}, []any{}); err != nil {
			t.Fatalf("register: %v", err)
		}
		var out any
		if err := dec.Decode(&out); err != nil {
			t.Fatalf("decode %s: %v (wire %s)", safeDesc(v), err, wireAnchor(b))
		}
		if d := rtFirstDiff(out, v); d != nil {
			t.Fatal(rtMismatchMsg(out, v, b, d))
		}
		// Secondary oracle: structural equality implies byte-identical
		// wire — the codec's canonical encoding re-derives the same
		// bytes from the decoded value. Divergence here is a fuzzing
		// finding, not a comparator defect, and fails loudly.
		b2, err := gbon.Marshal(out)
		if err != nil {
			t.Fatalf("re-marshal %s: %v (wire %s)", safeDesc(out), err, wireAnchor(b))
		}
		if !bytes.Equal(b, b2) {
			t.Fatalf("structural equal, wire diverged: original %s vs re-encoded %s", wireAnchor(b), wireAnchor(b2))
		}
	})
}

// rtGen builds the class-table value a FuzzRT seed selects: the closed
// 12-class table (int64/int32/string/X/*X/(*X)(nil)/nil/
// map[string]int/[]int64/map[string]any/[]any/map[any]int) with shared
// pointers, unhashable-key filtering for map[any]int, and self/mutual
// cycles through any positions. FuzzRT and the deterministic replay
// and mutation tests (TestRTComparatorSeeds/Mutations) share this
// single source.
func rtGen(seed int64) any {
	r := rand.New(rand.NewSource(seed))
	var pool []*X
	var mapPool []any
	var slicePool []any
	var mk func(depth int) any
	mk = func(depth int) any {
		if depth > 4 {
			return int64(r.Int63())
		}
		switch r.Intn(12) {
		case 0:
			return int64(r.Int63())
		case 1:
			return int32(r.Int31())
		case 2:
			return fmt.Sprintf("s%d", r.Intn(100))
		case 3:
			return X{N: int64(r.Int63())}
		case 4:
			if len(pool) > 0 && r.Intn(2) == 0 {
				return pool[r.Intn(len(pool))]
			}
			x := &X{N: int64(r.Int63())}
			pool = append(pool, x)
			return x
		case 5:
			return (*X)(nil)
		case 6:
			m := map[string]int{"a": r.Intn(9)}
			mapPool = append(mapPool, m)
			return m
		case 7:
			return nil
		case 8:
			// slice-dynamic in an any position: dynamic slice
			// type behind interface
			s := make([]int64, r.Intn(3))
			for i := range s {
				s[i] = r.Int63()
			}
			return s
		case 9:
			// Map self/mutual reference through any — Marshal
			// must terminate (visited set) and the cycle must close.
			m := map[string]any{}
			mapPool = append(mapPool, m)
			if len(mapPool) > 0 && r.Intn(2) == 0 {
				other := mapPool[r.Intn(len(mapPool))]
				m["back"] = other
			} else {
				m["self"] = m
			}
			return m
		case 10:
			// Slice self-reference through any.
			s := make([]any, r.Intn(3)+1)
			slicePool = append(slicePool, s)
			if len(slicePool) > 1 && r.Intn(2) == 0 {
				s[0] = slicePool[r.Intn(len(slicePool)-1)]
			} else {
				s[0] = s
			}
			for i := 1; i < len(s); i++ {
				s[i] = mk(depth + 1)
			}
			return s
		default:
			m := map[any]int{}
			for i, n := 0, r.Intn(4); i < n; i++ {
				k := mk(depth + 1)
				switch k.(type) {
				case map[string]int, map[any]int, []int64, map[string]any, []any:
					k = int64(r.Int63()) // unhashable dynamic key classes
				}
				m[k] = r.Intn(9)
			}
			return m
		}
	}
	return mk(0)
}

// rtDiff is the first divergent position a lockstep comparison found:
// the path from the root, and the differing sub-values at that path.
type rtDiff struct {
	path string
	got  any
	want any
}

// visPair identifies a visited (got, want) composite pair by address;
// the keep fields pin the objects so the addresses stay meaningful
// for the lifetime of one walk.
type visPair struct {
	a, b         uintptr
	keepA, keepB any
}

type rtCmp struct {
	visited []visPair
	diff    *rtDiff
}

func (c *rtCmp) fail(path string, got, want any) bool {
	if c.diff == nil {
		c.diff = &rtDiff{path: path, got: got, want: want}
	}
	return false
}

// seen registers a composite (got, want) pair and reports whether the
// walk is already inside it: a recurring pair closes the cycle, and
// everything reachable from it has already been compared on the first
// visit, so pair recursion counts as equal.
func (c *rtCmp) seen(a, b any) bool {
	pa, pb := reflect.ValueOf(a).Pointer(), reflect.ValueOf(b).Pointer()
	for i := range c.visited {
		if c.visited[i].a == pa && c.visited[i].b == pb {
			return true
		}
	}
	c.visited = append(c.visited, visPair{pa, pb, a, b})
	return false
}

// canonKey renders an map[any]int key class in a canonical string form:
// distinct keys over the mk() key classes (int64/int32/string/X/*X/
// (*X)(nil)/nil) always render distinctly, so key sets compare across
// the fresh pointer addresses a round-trip creates.
func canonKey(k any) string {
	switch x := k.(type) {
	case nil:
		return "nil"
	case *X:
		if x == nil {
			return "(*X)(nil)"
		}
		return "*X(" + strconv.FormatInt(x.N, 10) + ")"
	case X:
		return "X(" + strconv.FormatInt(x.N, 10) + ")"
	case int64:
		return "int64(" + strconv.FormatInt(x, 10) + ")"
	case int32:
		return "int32(" + strconv.FormatInt(int64(x), 10) + ")"
	default:
		return fmt.Sprintf("%T(%v)", k, k)
	}
}

// rtFirstDiff compares a decoded value against its generator original
// with a lockstep walk over the closed mk() class table: map entries
// match by canonical key forms at any nesting depth (no false mismatch
// from map iteration order or fresh pointer addresses), an injected
// mutation always surfaces as the first diff (no false equality), and
// the diff carries the divergent position for the failure reporter.
// nil returns mean structurally equal.
func rtFirstDiff(got, want any) *rtDiff {
	c := &rtCmp{}
	if !c.eq(got, want, "") {
		return c.diff
	}
	return nil
}

func (c *rtCmp) eq(a, b any, path string) bool {
	switch wb := b.(type) {
	case nil:
		if a != nil {
			return c.fail(path, a, "nil")
		}
		return true
	case int64:
		wa, ok := a.(int64)
		if !ok || wa != wb {
			return c.fail(path, a, wb)
		}
		return true
	case int32:
		wa, ok := a.(int32)
		if !ok || wa != wb {
			return c.fail(path, a, wb)
		}
		return true
	case string:
		wa, ok := a.(string)
		if !ok || wa != wb {
			return c.fail(path, a, wb)
		}
		return true
	case X:
		wa, ok := a.(X)
		if !ok || wa.N != wb.N {
			return c.fail(path, a, wb)
		}
		return true
	case *X:
		wa, ok := a.(*X)
		if !ok || (wa == nil) != (wb == nil) {
			return c.fail(path, a, wb)
		}
		if wa != nil && wa.N != wb.N {
			return c.fail(path, a, wb)
		}
		return true
	case map[string]int:
		wa, ok := a.(map[string]int)
		if !ok {
			return c.fail(path, a, wb)
		}
		if len(wa) != len(wb) {
			return c.fail(path, wa, wb)
		}
		for k, wv := range wb {
			av, ok := wa[k]
			if !ok {
				return c.fail(path+"."+strconv.Quote(k), "<absent>", wv)
			}
			if av != wv {
				return c.fail(path+"."+strconv.Quote(k), av, wv)
			}
		}
		return true
	case []int64:
		wa, ok := a.([]int64)
		if !ok || len(wa) != len(wb) {
			return c.fail(path, a, wb)
		}
		for i := range wb {
			if wa[i] != wb[i] {
				return c.fail(path+"["+strconv.Itoa(i)+"]", wa[i], wb[i])
			}
		}
		return true
	case map[string]any:
		wa, ok := a.(map[string]any)
		if !ok {
			return c.fail(path, a, wb)
		}
		if len(wa) != len(wb) {
			return c.fail(path, wa, wb)
		}
		if c.seen(a, b) {
			return true
		}
		for k, wv := range wb {
			av, ok := wa[k]
			if !ok {
				return c.fail(path+"."+k, "<absent>", wv)
			}
			if !c.eq(av, wv, path+"."+k) {
				return false
			}
		}
		return true
	case []any:
		wa, ok := a.([]any)
		if !ok || len(wa) != len(wb) {
			return c.fail(path, a, wb)
		}
		if c.seen(a, b) {
			return true
		}
		for i := range wb {
			if !c.eq(wa[i], wb[i], path+"["+strconv.Itoa(i)+"]") {
				return false
			}
		}
		return true
	case map[any]int:
		wa, ok := a.(map[any]int)
		if !ok {
			return c.fail(path, a, wb)
		}
		if len(wa) != len(wb) {
			return c.fail(path, wa, wb)
		}
		gc := map[string]int{}
		for k, v := range wa {
			gc[canonKey(k)] = v
		}
		for k, wv := range wb {
			ck := canonKey(k)
			gv, ok := gc[ck]
			if !ok {
				return c.fail(path+".["+ck+"]", "<absent>", wv)
			}
			if gv != wv {
				return c.fail(path+".["+ck+"]", gv, wv)
			}
		}
		return true
	default:
		// The mk() class table is closed; a want-side value outside it
		// is a generator defect — loud, never a silent pass.
		panic(fmt.Sprintf("rtCmp: want-side class %T outside the mk() table", b))
	}
}

// safeDesc renders a fuzz value for failure messages without recursing
// into cycles: a depth-capped structural walk over the closed mk() class
// table (sharing edges render as their node summary), with a type-only
// fallback for anything else. %#v on a cyclic value kills the process
// with a stack overflow, so failure reports never format raw values.
func safeDesc(v any) string {
	var sb strings.Builder
	var walk func(v any, d int)
	walk = func(v any, d int) {
		if v == nil {
			sb.WriteString("nil")
			return
		}
		if d >= 8 {
			fmt.Fprintf(&sb, "%T…", v)
			return
		}
		switch x := v.(type) {
		case int, int64, int32, string:
			fmt.Fprintf(&sb, "%T(%v)", x, x)
		case X:
			fmt.Fprintf(&sb, "X{N:%d}", x.N)
		case *X:
			if x == nil {
				sb.WriteString("(*X)(nil)")
			} else {
				fmt.Fprintf(&sb, "&X{N:%d}", x.N)
			}
		case map[string]int:
			fmt.Fprintf(&sb, "map[string]int{%d}", len(x))
		case []int64:
			fmt.Fprintf(&sb, "[]int64{%d}", len(x))
		case map[string]any:
			sb.WriteString("map[string]any{")
			for _, k := range []string{"self", "back"} {
				if e, ok := x[k]; ok {
					sb.WriteString(k + ":")
					walk(e, d+1)
				}
			}
			fmt.Fprintf(&sb, "}(%d)", len(x))
		case []any:
			fmt.Fprintf(&sb, "[]any{%d}[0]=", len(x))
			if len(x) > 0 {
				walk(x[0], d+1)
			}
		case map[any]int:
			fmt.Fprintf(&sb, "map[any]int{%d}", len(x))
		default:
			fmt.Fprintf(&sb, "%T", v)
		}
	}
	walk(v, 0)
	return sb.String()
}

// wireAnchor pins the marshal output a failure report refers to:
// total length plus a bounded hex prefix.
func wireAnchor(b []byte) string {
	n := min(len(b), 32)
	return fmt.Sprintf("%dB:%x", len(b), b[:n])
}

// rtMismatchMsg builds the round-trip failure report: the first
// divergent position with local cycle-safe renders of both sides at
// that position, root-level structural summaries of both values, and
// the wire anchor. The got/want halves are never byte-identical: a
// collapsed render would hide the distinguishing datum the contract
// (codec_fuzz_test fuzzrt-cyclic-print) requires, so equal renders are
// re-suffixed until they differ.
func rtMismatchMsg(out, v any, b []byte, d *rtDiff) string {
	gd, wd := safeDesc(d.got), safeDesc(d.want)
	if gd == wd {
		gd, wd = fmt.Sprintf("%T %s", d.got, gd), fmt.Sprintf("%T %s", d.want, wd)
	}
	if gd == wd {
		gd, wd = gd+" (got)", wd+" (want)"
	}
	return fmt.Sprintf("round-trip mismatch at %s:\n got %s\nwant %s\nroot got %T %s\nroot want %T %s\nwire %s",
		d.path, gd, wd, out, safeDesc(out), v, safeDesc(v), wireAnchor(b))
}

// TestSafeDescCyclic: the failure reporters survive the cyclic classes the
// generator builds (self/mutual map references, self-slices) and the
// mismatch message carries every component an RT bug report needs
// (fuzzrt-cyclic-print).
func TestSafeDescCyclic(t *testing.T) {
	self := map[string]any{}
	self["self"] = self
	mutA := map[string]any{}
	mutB := map[string]any{}
	mutA["back"] = mutB
	mutB["back"] = mutA
	s := make([]any, 2)
	s[0] = s
	s[1] = &X{N: 7}
	for _, v := range []any{self, mutA, s, map[any]int{"k": 1}, (*X)(nil)} {
		d := safeDesc(v)
		if len(d) == 0 || len(d) > 4096 {
			t.Fatalf("desc of %T: len %d", v, len(d))
		}
	}
	if safeDesc(X{N: 1}) == safeDesc(&X{N: 1}) {
		t.Fatalf("X vs *X collapse in descriptions")
	}
	if safeDesc(int64(7)) == safeDesc(int32(7)) {
		t.Fatalf("scalar width collapse in descriptions")
	}
	selfMsg := safeDesc(self)
	for _, want := range []string{"map[string]any{", "self:map[string]any{", "map[string]interface {}…", "}(1)"} {
		if !strings.Contains(selfMsg, want) {
			t.Fatalf("self description missing %q: %s", want, selfMsg)
		}
	}
	if !strings.Contains(safeDesc([]int64{1, 2, 3}), "[]int64{3}") {
		t.Fatalf("slice length datum lost")
	}
	if !strings.Contains(safeDesc(map[string]int{"a": 1, "b": 2}), "map[string]int{2}") {
		t.Fatalf("map length datum lost")
	}
	msg := rtMismatchMsg(map[string]int{"a": 1}, self, []byte{0x61, 0x6e}, rtFirstDiff(map[string]int{"a": 1}, self))
	for _, want := range []string{"map[string]int", "map[string]interface", "wire 2B:", "self:"} {
		if !strings.Contains(msg, want) {
			t.Fatalf("message missing %q:\n%s", want, msg)
		}
	}
	if len(msg) > 4096 {
		t.Fatalf("message over bound: %d", len(msg))
	}
	// A pair whose descriptions share an identical prefix at least
	// three containers deep and diverge below the old safeDesc cap of
	// 3 (the crasher-seed-1280 shape: a map[any]int nested inside
	// cyclic containers) — the report must still carry a divergent
	// position, non-identical got/want halves, and a distinguishing
	// datum.
	mkDeep := func(leaf int64) any {
		inner := map[any]int{int64(leaf): 1}
		w := map[string]any{}
		s := []any{map[string]any{"k": []any{inner}}}
		w["self"] = w
		w["d"] = s
		return w
	}
	gotV, wantV := mkDeep(9), mkDeep(7)
	d := rtFirstDiff(gotV, wantV)
	if d == nil {
		t.Fatalf("deep mutation below old cap not detected")
	}
	if !strings.Contains(d.path, ".d[0].k[0].[int64(7)]") {
		t.Fatalf("diff path %q does not point at the mutated position", d.path)
	}
	wire, err := gbon.Marshal(wantV)
	if err != nil {
		t.Fatal(err)
	}
	deepMsg := rtMismatchMsg(gotV, wantV, wire, d)
	lines := strings.Split(deepMsg, "\n")
	if len(lines) < 3 || lines[1] == lines[2] {
		t.Fatalf("got/want halves byte-identical:\n%s", deepMsg)
	}
	if !strings.Contains(deepMsg, "int64(7)") {
		t.Fatalf("distinguishing datum lost:\n%s", deepMsg)
	}
	if !strings.Contains(deepMsg, "wire ") {
		t.Fatalf("wire anchor lost:\n%s", deepMsg)
	}
}

// TestRTComparatorSeeds replays FuzzRT deterministically: for a fixed
// seed list (the crasher seed 1280 — data "\x000000", seed arithmetic
// len<<8|data[0] — included) the generated value goes through
// Marshal→Decode, the lockstep comparator finds no divergence at any
// nesting depth, and the re-encoded wire is byte-identical — a
// permanent isomorphism pin for every listed seed.
func TestRTComparatorSeeds(t *testing.T) {
	seeds := []int64{0, 1, 2, 3, 4, 5, 6, 7, 1280, 1281, 1282, 4096, 65535, 1 << 20}
	for _, seed := range seeds {
		v := rtGen(seed)
		b, err := gbon.Marshal(v)
		if err != nil {
			t.Fatalf("seed %d: marshal: %v", seed, err)
		}
		dec := gbon.NewDecoder(bytes.NewReader(b))
		if err := dec.Register(int64(0), int32(0), X{}, &X{}, "", map[string]int{}, map[any]int{}, []int64{}, map[string]any{}, []any{}); err != nil {
			t.Fatalf("seed %d: register: %v", seed, err)
		}
		var out any
		if err := dec.Decode(&out); err != nil {
			t.Fatalf("seed %d: decode: %v (wire %s)", seed, err, wireAnchor(b))
		}
		if d := rtFirstDiff(out, v); d != nil {
			t.Fatalf("seed %d: false mismatch:\n%s", seed, rtMismatchMsg(out, v, b, d))
		}
		b2, err := gbon.Marshal(out)
		if err != nil {
			t.Fatalf("seed %d: re-marshal: %v", seed, err)
		}
		if !bytes.Equal(b, b2) {
			t.Fatalf("seed %d: wire diverged: original %s vs re-encoded %s", seed, wireAnchor(b), wireAnchor(b2))
		}
	}
}

// TestRTComparatorMutations: an injected mutation in any position the
// generator table can build — below the old safeDesc cap of 3 and
// inside cyclic containers included — must land in the comparator's
// first diff with the reported path pointing at the mutated position.
func TestRTComparatorMutations(t *testing.T) {
	mkLeaf := func(leaf int64) any {
		return []any{[]any{[]any{[]any{leaf}}}}
	}
	mkX := func(n int64) any {
		return []any{[]any{[]any{[]any{X{N: n}}}}}
	}
	mkNilKind := func(typed bool) any {
		var leaf any
		if typed {
			leaf = (*X)(nil)
		}
		return []any{[]any{[]any{[]any{leaf}}}}
	}
	mkCycleStr := func(s string) any {
		w := map[string]any{}
		w["self"] = w
		w["s"] = s
		return w
	}
	mkCycleSlice := func(leaf int64) any {
		s := make([]any, 2)
		s[0] = s
		s[1] = []any{leaf}
		return s
	}
	mkStarKeys := func(n int64, v int) any {
		return []any{map[any]int{&X{N: n}: v}}
	}
	cases := []struct {
		name     string
		got      any
		want     any
		wantPath string
	}{
		{"int64 leaf below old cap", mkLeaf(9), mkLeaf(7), "[0][0][0][0]"},
		{"X.N below old cap", mkX(2), mkX(1), "[0][0][0][0]"},
		{"map length", map[string]int{"a": 1, "b": 2}, map[string]int{"a": 1}, ""},
		{"nil vs (*X)(nil) below old cap", mkNilKind(false), mkNilKind(true), "[0][0][0][0]"},
		{"string value inside cyclic map", mkCycleStr("s2"), mkCycleStr("s1"), ".s"},
		{"int64 leaf inside cyclic slice", mkCycleSlice(9), mkCycleSlice(7), "[1][0]"},
		{"*X key identity in map[any]int", mkStarKeys(6, 1), mkStarKeys(5, 1), "[0].[*X(5)]"},
		{"key value in map[any]int", mkStarKeys(5, 2), mkStarKeys(5, 1), "[0].[*X(5)]"},
	}
	for _, tc := range cases {
		d := rtFirstDiff(tc.got, tc.want)
		if d == nil {
			t.Errorf("%s: false equality (comparator missed the mutation)", tc.name)
			continue
		}
		if !strings.Contains(d.path, tc.wantPath) {
			t.Errorf("%s: diff path %q does not contain mutated position %q", tc.name, d.path, tc.wantPath)
		}
		msg := rtMismatchMsg(tc.got, tc.want, nil, d)
		lines := strings.Split(msg, "\n")
		if len(lines) < 3 || lines[1] == lines[2] {
			t.Errorf("%s: got/want halves byte-identical:\n%s", tc.name, msg)
		}
	}
}

const (
	fuzzCorpusFileCap = 64
	fuzzCorpusByteCap = 256 << 10
)

// checkCorpusCaps walks a fuzz corpus root (testdata/fuzz/<Target>/…)
// and reports cap violations: more than fuzzCorpusFileCap seed files
// or more than fuzzCorpusByteCap per target.
func checkCorpusCaps(root string) []string {
	var violations []string
	entries, err := os.ReadDir(root)
	if err != nil {
		return []string{fmt.Sprintf("read %s: %v", root, err)}
	}
	for _, e := range entries {
		if !e.IsDir() {
			continue
		}
		target := filepath.Join(root, e.Name())
		files, err := os.ReadDir(target)
		if err != nil {
			violations = append(violations, fmt.Sprintf("read %s: %v", target, err))
			continue
		}
		var total int64
		for _, f := range files {
			if f.IsDir() {
				continue
			}
			fi, err := f.Info()
			if err != nil {
				violations = append(violations, fmt.Sprintf("stat %s: %v", f.Name(), err))
				continue
			}
			total += fi.Size()
		}
		if len(files) > fuzzCorpusFileCap {
			violations = append(violations, fmt.Sprintf("fuzz corpus %s: %d files > cap %d", e.Name(), len(files), fuzzCorpusFileCap))
		}
		if total > fuzzCorpusByteCap {
			violations = append(violations, fmt.Sprintf("fuzz corpus %s: %d bytes > cap %d", e.Name(), total, fuzzCorpusByteCap))
		}
	}
	return violations
}

// TestFuzzCorpusCap: the committed seed corpus stays bounded — at
// most 64 files and 256 KiB per fuzz target — so replaying every
// seed in every `go test` run never becomes a runtime liability.
// Corpus growth is an explicit decision: a new seed lands as a
// reviewed commit, never as quietly accumulated state.
func TestFuzzCorpusCap(t *testing.T) {
	for _, v := range checkCorpusCaps("testdata/fuzz") {
		t.Error(v)
	}
}

// TestFuzzCorpusCapRejects: the negative fixture for the corpus cap
// checker — a synthetic target over the file cap must be reported
// with its numbers, so a green run proves the checker rejects rather
// than silently passes.
func TestFuzzCorpusCapRejects(t *testing.T) {
	root := t.TempDir()
	dir := filepath.Join(root, "FuzzSynthetic")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		t.Fatal(err)
	}
	for i := 0; i <= fuzzCorpusFileCap; i++ {
		if err := os.WriteFile(filepath.Join(dir, fmt.Sprintf("seed-%d", i)), []byte("x"), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	vs := checkCorpusCaps(root)
	if len(vs) != 1 {
		t.Fatalf("violations = %v, want exactly the file-cap report", vs)
	}
	if !strings.Contains(vs[0], "files > cap") || !strings.Contains(vs[0], fmt.Sprint(fuzzCorpusFileCap+1)) {
		t.Fatalf("violation %q missing cap numbers", vs[0])
	}
}

// FuzzTrustedWindow: the trusted-input capture over arbitrary input.
// Every decode error carrying an offset captures a window within the
// 32+16 bound, the verbose render carries exactly one marked line at the
// clamped offset-1 position, and the default (unflagged) decode of the
// same input never renders the block.
func FuzzTrustedWindow(f *testing.F) {
	for _, v := range []any{int64(7), "MARKERSTR", []int64{1, 2, 3}, map[string]int64{"k": 1}} {
		b, err := gbon.Marshal(v)
		if err != nil {
			f.Fatal(err)
		}
		f.Add(b)
		f.Add(b[:len(b)/2])
		flip := append([]byte{}, b...)
		flip[len(flip)/2] ^= 0xFF
		f.Add(flip)
	}
	f.Fuzz(func(t *testing.T, data []byte) {
		td := gbon.NewDecoder(bytes.NewReader(data))
		td.SetTrustedInput(true)
		var tv any
		terr := td.Decode(&tv)

		dd := gbon.NewDecoder(bytes.NewReader(data))
		var dv any
		derr := dd.Decode(&dv)
		if (terr == nil) != (derr == nil) {
			t.Fatalf("trust flag changed the outcome: %v vs %v", terr, derr)
		}
		if terr == nil {
			return
		}
		if errors.Is(terr, io.EOF) || errors.Is(derr, io.EOF) {
			if (errors.Is(terr, io.EOF)) != (errors.Is(derr, io.EOF)) {
				t.Fatalf("trust flag changed the EOF outcome: %v vs %v", terr, derr)
			}
			return
		}
		var tae, dae *gbon.Error
		if !errors.As(terr, &tae) || !errors.As(derr, &dae) {
			t.Fatalf("not As-recoverable: %v", terr)
		}
		if tae.Class() != dae.Class() || tae.Offset != dae.Offset || tae.Error() != dae.Error() {
			t.Fatalf("trust flag changed the error: %v vs %v", terr, derr)
		}
		if strings.Contains(fmt.Sprintf("%+v", dae), "input =") {
			t.Fatalf("default render carries the window block: %+v", dae)
		}
		if tae.Offset < 0 {
			if _, ok := tae.Snippet(); ok {
				t.Fatalf("offset-less error captured a window: %+v", tae)
			}
			return
		}
		sn, ok := tae.Snippet()
		if !ok {
			t.Fatalf("decode error with offset lacks a window: %+v", tae)
		}
		if sn.ByteLength < 0 || sn.ByteLength > 48 {
			t.Fatalf("window length %d outside [0,48]", sn.ByteLength)
		}
		if sn.ByteLength == 0 {
			if strings.Contains(fmt.Sprintf("%+v", tae), "input =") {
				t.Fatalf("empty window rendered a block: %+v", tae)
			}
			return
		}
		verbose := fmt.Sprintf("%+v", tae)
		const header = "\n    input =\n"
		_, after, ok := strings.Cut(verbose, header)
		if !ok {
			t.Fatalf("captured window missing from the render: %+v", tae)
		}
		lines := strings.Split(after, "\n")
		marked := max(tae.Offset-1, sn.ByteOffset)
		if last := sn.ByteOffset + sn.ByteLength - 1; marked > last {
			marked = last
		}
		wantLine := 1 + (marked-sn.ByteOffset)/16
		seen := 0
		for j, ln := range lines {
			if strings.HasPrefix(ln, "=> ") {
				seen++
				if j+1 != wantLine {
					t.Fatalf("marked line %d, want %d (marked byte %d, window %d..%d):\n%s",
						j+1, wantLine, marked, sn.ByteOffset, sn.ByteOffset+sn.ByteLength, verbose)
				}
			}
		}
		if seen != 1 {
			t.Fatalf("marked lines = %d, want 1:\n%s", seen, verbose)
		}
	})
}
